CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(80)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE bird (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id         BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name             VARCHAR(60) NOT NULL,
    species          VARCHAR(60) NOT NULL,
    color_mutation   VARCHAR(60),
    sex              VARCHAR(10) NOT NULL,
    hatch_date       DATE,
    target_min_grams DOUBLE PRECISION NOT NULL,
    target_max_grams DOUBLE PRECISION NOT NULL,
    notes            VARCHAR(1000),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_bird_owner ON bird (owner_id);

CREATE TABLE weight_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bird_id     BIGINT           NOT NULL REFERENCES bird (id) ON DELETE CASCADE,
    grams       DOUBLE PRECISION NOT NULL,
    measured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    note        VARCHAR(500)
);
CREATE INDEX idx_weight_bird_time ON weight_entry (bird_id, measured_at);

CREATE TABLE care_task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bird_id           BIGINT       NOT NULL REFERENCES bird (id) ON DELETE CASCADE,
    type              VARCHAR(30)  NOT NULL,
    title             VARCHAR(100) NOT NULL,
    interval_days     INT          NOT NULL,
    last_completed_at TIMESTAMP WITH TIME ZONE,
    next_due_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    active            BOOLEAN      NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_care_task_bird ON care_task (bird_id);
CREATE INDEX idx_care_task_due ON care_task (active, next_due_at);

CREATE TABLE health_alert (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bird_id      BIGINT       NOT NULL REFERENCES bird (id) ON DELETE CASCADE,
    care_task_id BIGINT REFERENCES care_task (id) ON DELETE SET NULL,
    type         VARCHAR(30)  NOT NULL,
    severity     VARCHAR(10)  NOT NULL,
    message      VARCHAR(500) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at  TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_alert_bird_open ON health_alert (bird_id, resolved_at);
